" Import Pathogen
execute pathogen#infect()

" Set the leader char to comma
let mapleader = ","

" Enable syntax highlighting
syntax on
filetype plugin indent on

" Default tab settings
set shiftwidth=4
set tabstop=4
set expandtab

" Enable 256 color mode
set t_Co=256

" Make sure numbering works right with numbers plugin
set number

" Set up omnicompletion
let g:acp_enableAtStartup = 0
let g:neocomplcache_enable_at_startup = 1
let g:neocomplcache_enable_smart_case = 1
let g:neocomplcache_min_syntax_length = 3
let g:neocomplcache_lock_buffer_name_pattern = '\*ku\*'
let g:neocomplcache_enable_auto_select = 1
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

" Neocomplcache key bindings
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function()
	"return neocomplcache#smart_close_popup() . "\<CR>"
	" For no inserting <CR> key.
	return pumvisible() ? neocomplcache#close_popup() : "\<CR>"
endfunction
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"

" Enable airline fonts
let g:airline_powerline_fonts = 1

" Set color scheme
set background=dark
colorscheme wombat256mod

