" Specify a directory for plugins
call plug#begin('~/.vim/plug')

Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-sensible'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'airblade/vim-gitgutter'
Plug 'itchyny/lightline.vim'
Plug 'liuchengxu/vim-which-key'
Plug 'liuchengxu/vim-better-default'

" Themes
Plug 'haishanh/night-owl.vim'
Plug 'tyrannicaltoucan/vim-quantum'

" Initialize plugin system
call plug#end()

" Set the leader char to space 
let mapleader = " "
nnoremap <silent> <leader> :WhichKey '<Space>'<CR>

" Enable syntax highlighting
syntax on
filetype plugin indent on

" Set theme
set background=dark
set termguicolors
let g:quantum_black=1
colorscheme quantum
let g:lightline = { 'colorscheme': 'quantum' }

" Enable search highlighting
set hlsearch

" Default tab settings
set shiftwidth=2
set tabstop=2
set expandtab

" Move backup/swp files to .vimbackups
silent execute '!mkdir ~/.vimbackups'
set backupdir=~/.vimbackups//
set directory=~/.vimbackups//

" Git (fugitive) shortcuts
nmap <leader>gd :Gdiff<cr>
nmap <leader>gc :Gcommit<cr>
nmap <leader>gs :Gstatus<cr>
nmap <leader>ga :Gwrite<cr>

" Enable mouse clicks to move cursor
:set mouse=a
