#!/bin/sh

GREEN='\033[1;32m'
BLUE='\033[1;34m'
NC='\033[0m'

echo
echo -e "${GREEN}Updating ${BLUE}$(hostname)${GREEN}...${NC}"
echo

sudo -E guix system -L ~/.config/guix/systems reconfigure ~/.config/guix/systems/$(hostname).scm
